add en- and decoding to municipality routing
Klimatbyran/klimatkollen pull request #493
Opened 2024-05-03 07:15 UTC by elvbom

Add en- and decoding to municipality routing as well as minor cleanup

Fix #

2024-05-06 07:49 UTC, Greenheart requested changes
One typo bit apart from that it looks good.

I will test properly in a moment.

2024-05-06 07:49 UTC, Greenheart commented on __tests__/utils/generateMunipacitySitemap.test.ts
> +  generateMunicipacitySitemapData,
```suggestion
  generateMunicipalitySitemapData,
```

2024-05-06 07:49 UTC, Greenheart commented on __tests__/utils/generateMunipacitySitemap.test.ts
> +    const siteMap = generateMunicipacitySitemapData({ municipalities })
```suggestion
    const siteMap = generateMunicipalitySitemapData({ municipalities })
```

2024-05-06 07:49 UTC, Greenheart commented on __tests__/utils/generateMunipacitySitemap.test.ts
> +    const siteMap = generateMunicipacitySitemapData({ municipalities })
```suggestion
    const siteMap = generateMunicipalitySitemapData({ municipalities })
```

2024-05-06 07:49 UTC, Greenheart commented on pages/sitemap.xml.ts
> +  generateMunicipacitySitemapData,
```suggestion
  generateMunicipalitySitemapData,
```

2024-05-06 07:49 UTC, Greenheart commented on pages/sitemap.xml.ts
> +  const municipalitiesSitemap = generateMunicipacitySitemapData({ municipalities })
```suggestion
  const municipalitiesSitemap = generateMunicipalitySitemapData({ municipalities })
```

2024-05-06 07:49 UTC, Greenheart commented on utils/generateMunipacitySitemap.ts
> +export const generateMunicipacitySitemapData = ({
```suggestion
export const generateMunicipalitySitemapData = ({
```

2024-05-06 08:45 UTC, Greenheart approved these changes
Tested and this is a confirmed solution for #469 :)

2024-05-06 08:45 UTC, merged

2024-05-11 17:02 UTC, LudwikJaniuk commented
"munipacility" <3 I think we should just make that the correct term...