Deploy to production
Klimatbyran/klimatkollen pull request #599
Opened 2024-05-27 07:59 UTC by Greenheart

## Included changes

- Show map view first for municipalities
- Remove duplicated words in company data
- Remove unused Borna font assets
- Improved table UX, scrolling the full page, sticky table header and table footer. Improved layout on smaller screen sizes.
- Updated tests for SMHI data
- Removed old data output files and move consumption data to Excel
- Feature: Make Python tests for SMHI data independent from the last year with data

2024-05-28 13:42 UTC, Greenheart commented
As soon as https://github.com/Klimatbyran/klimatkollen/pull/602 is merged, we can test and deploy this.

2024-05-29 08:44 UTC, elvbom commented on data/output/climate-data.json
This data is incorrect. I'll fix in a new PR which should be included in this release

2024-05-29 09:32 UTC, Greenheart commented on data/output/climate-data.json
Ok, good catch!

2024-05-29 09:45 UTC, elvbom requested changes
The table footer font size is rather small on desktop, can it be made larger?

<img width="818" alt="Screenshot 2024-05-29 at 10 51 20" src="https://github.com/Klimatbyran/klimatkollen/assets/7899748/f87f58b5-705e-411f-822d-37798ab0f1f0">

2024-05-29 12:15 UTC, elvbom approved these changes

2024-05-29 12:15 UTC, merged