Speed up data processing
Klimatbyran/klimatkollen pull request #683
Opened 2024-09-22 00:09 UTC by joakimbits

Closes #682 by adding a test profiling tool, a faster excel parser and a DataFrame caching decorator. Reduces test suite execution time from 15 seconds to 8 seconds on first run and 0.3 seconds on second run when tested on a Mac Air M1.

2024-09-26 15:33 UTC, elvbom requested changes
Great work! I got a minor error, would love to hear your thoughts on it

2024-09-26 19:20 UTC, joakimbits commented on data/issues/emissions/historical_data_calculations.py
> +    df_raw = pd.read_excel(path, engine="calamine")
python -m pip install -r requiremens.txt

Funkar det sen?

Jag lade till calamine där och pandas skall hitta det sen när det är installerat.

2024-09-30 12:52 UTC, joakimbits commented on data/issues/emissions/historical_data_calculations.py
> +    df_raw = pd.read_excel(path, engine="calamine")
@elvbom Kanske jag skall göra Calamine optional? Calamine snabbar upp den här read_excel med 6 sekunder, men den stora förbättringen är cache_df som tar nolltid efter en första read_excel.

2024-10-09 11:32 UTC, elvbom commented on data/issues/emissions/historical_data_calculations.py
> +    df_raw = pd.read_excel(path, engine="calamine")
Jag provade med xlrd och openpyxl vilket funkade, tror du det skulle vara en idé att använda ngn av dem istället? Jag är inte bekant med calamine sedan tidigare men tänker att alternativen ovan brukar vara bra val för parsing av Excel-filer med pandas

2024-10-15 07:46 UTC, joakimbits commented on data/issues/emissions/historical_data_calculations.py
> +    df_raw = pd.read_excel(path, engine="calamine")
Ja vad bra! Men blir det lika snabbt som Calamine? Jag kollar!

2024-10-15 08:19 UTC, joakimbits commented on data/issues/emissions/historical_data_calculations.py
> +    df_raw = pd.read_excel(path, engine="calamine")
`quflow@Joakims-MacBook-Air data % py.test tests`

* 8 sekunder `pd.read_excel(path, engine="calamine")`
* 9 sekunder `pd.read_excel(path, engine="openpyxl")`
* 17 sekunder `pd.read_excel(path)`

Xlrd funkade inte med SMHI data: `FAILED tests/test_emission_calculations.py::TestEmissionCalculations::test_get_n_prep_data_from_smhi - xlrd.biffh.XLRDError: Excel xlsx file; not supported`

Jag byter till openpyxl!

2024-10-23 12:25 UTC, elvbom approved these changes
Bra jobbat! :)

2024-10-23 12:35 UTC, merged